# Name: Fatima Asim
# Roll No.: 20i-0847
# Assignment 6

# Instruction

1. Don’t plagiarize, Plagiarism would lead to straight zero
2. Clearly mention your NAME and ROLL NO#.
3. Late submissions are not allowed. Start Early.

In [ ]:
#!pip install bs4
#!pip install selenium
#!pip install webdriver-manager

In [3]:
#import libraries
import time
import pandas as pd
import warnings
from selenium import webdriver
from selenium.webdriver.edge.options import Options
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import ElementClickInterceptedException

# Question 1  (10 marks)

Scrape 3 pages of reviews for a single product listing using product URL.<br /> Note: Product must have more than 1 review page. The code must be generic and should work for every product listing URL, with proper checks in place.

In [106]:
url ='https://www.daraz.pk/products/led-i130007608-s1289825549.html?spm=a2a0e.searchlist.list.19.582f57dexFqLur&search=1'

In [107]:

warnings.filterwarnings("ignore")
driver = webdriver.Chrome(executable_path=r"C:\Users\asimf\Downloads\chromedriver.exe")

In [108]:
driver.get(url)

In [109]:
rev=driver.find_element("xpath", '//*[@id="module_product_review_star_1"]/div/a[1]')
rev=rev.text.split()
rev_int=int(rev[0])
rev_int

425

In [110]:


Names=[]
Review=[]
n=""
b=""
j=2
if rev_int>5: #if more than 1 page
    while(j<=4):
        i=1
        while(i<=5):
            try:
                n=driver.find_element("xpath",f'//*[@id="module_product_review"]/div/div/div[3]/div[1]/div[{i}]/div[2]/span[1]')
                Names.append(n.text[3:])
                print(n.text[3:])
                b=driver.find_element("xpath",f'//*[@id="module_product_review"]/div/div/div[3]/div[1]/div[{i}]/div[3]/div[1]')
                Review.append(b.text)
            except NoSuchElementException:
                Review.append("NaN")
                print("exception handled")
            i=i+1
            time.sleep(2)  
        try:
            print(j)
            e=driver.find_element(By.XPATH,f"/html/body/div[4]/div/div[9]/div[1]/div[2]/div/div/div/div[3]/div[2]/div/div/button[{j}]")
            time.sleep(7)
            e.click()
            time.sleep(7)
            j=j+1
        except NoSuchElementException:
            break
        except ElementClickInterceptedException:
            print("No "+str(j)+" page.")
            break

elif rev_int==1:
    try:
        n=driver.find_element("xpath",'/html/body/div[4]/div/div[9]/div[1]/div[2]/div/div/div/div[3]/div/div/div[2]/span[1]')
        Names.append(n.text[3:])
        b=driver.find_element("xpath",'//*[@id="module_product_review"]/div/div/div[3]/div[1]/div[1]/div[3]/div[1]')
        Review.append(b.text)
    except NoSuchElementException:
            Review.append("NaN")
            time.sleep(2) 
elif rev_int==0:
    print("no reviews")
else:
    for i in range(1,6):
        try:
            
            n=driver.find_element("xpath",f'//*[@id="module_product_review"]/div/div/div[3]/div[1]/div[{i}]/div[2]/')
            Names.append(n.text[3:])
            print(n.text[3:])
            b=driver.find_element("xpath",f'//*[@id="module_product_review"]/div/div/div[3]/div[1]/div[{i}]/div[3]/div[1]')
            Review.append(b.text)
        except NoSuchElementException:
            Review.append("NaN")
            time.sleep(2)  
        
        
driver.close()
if(len(Names)!=len(Review)): #removing exception handling junk data so names and reveiew can be of same lenght
    c=len(Review)-len(Names)
    Review=Review[:len(Review) - c]

Mustafa Y.
SULTAN
****7
muzamil
Z***.
2
Huzaifa G.
TARIQ M.
Saad M.
Muhammad A.
Ali R.
3
Talha J.
3***5
Äñäs M.
Muhammad K.
jahanzaib A.
4

In [111]:
df = pd.DataFrame({'Name':Names,'Review text':Review})

In [129]:
tf=df

In [112]:
#Output
df

            Name                                        Review text
0     Mustafa Y.  Luminous is very Awesome\nPortability is very ...
1         SULTAN  literally i got the thing beyond my expectatio...
2          ****7  Awesome product.I personally like this .And it...
3        muzamil  Seems to be a good product just received in a ...
4          Z***.  light bht achi ha....porey room ko achi trha r...
5     Huzaifa G.  it is a amazing lamp its helps me alot in my s...
6       TARIQ M.  Amazing beautiful smart product, packed carefu...
7        Saad M.  same product as shown in the picture very sati...
8    Muhammad A.  Original product.  The seller is trustworthy a...
9         Ali R.  Quality : 10/10\nDelivery: 10/10\nProduct expe...
10      Talha J.  Very good product especially in this price ran...
11         3***5  Good for 800ish Pkr (I think). Two problems. O...
12       Äñäs M.  unexpectedly extreme quality product in such a...
13   Muhammad K.  Reviewing after 1 month of use.\n\nI am workin...
14  jahanzaib A.  This product is really amazing 😍 . Great resul...

### Question 1 Part b  (10 marks)

Clean the Reviews using NLTK,RE. Remove Punctuations, Smilies and other garbage using any library. 

Apply Vader Sentiment to find the sentiment of the review, and append it in a column named "Sentiment".

You can get help of Vader sentiment from this; https://towardsdatascience.com/sentimental-analysis-using-vader-a3415fef7664

In [78]:
import numpy as np
import regex

In [113]:
df['Review text'].replace('', np.nan, inplace=True) #removing and cleaning data
df.dropna(subset=['Review text'], inplace=True)
df.reset_index(drop=True, inplace=True)
df

            Name                                        Review text
0     Mustafa Y.  Luminous is very Awesome\nPortability is very ...
1         SULTAN  literally i got the thing beyond my expectatio...
2          ****7  Awesome product.I personally like this .And it...
3        muzamil  Seems to be a good product just received in a ...
4          Z***.  light bht achi ha....porey room ko achi trha r...
5     Huzaifa G.  it is a amazing lamp its helps me alot in my s...
6       TARIQ M.  Amazing beautiful smart product, packed carefu...
7        Saad M.  same product as shown in the picture very sati...
8    Muhammad A.  Original product.  The seller is trustworthy a...
9         Ali R.  Quality : 10/10\nDelivery: 10/10\nProduct expe...
10      Talha J.  Very good product especially in this price ran...
11         3***5  Good for 800ish Pkr (I think). Two problems. O...
12       Äñäs M.  unexpectedly extreme quality product in such a...
13   Muhammad K.  Reviewing after 1 month of use.\n\nI am workin...
14  jahanzaib A.  This product is really amazing 😍 . Great resul...

In [114]:
df.astype(str).apply(lambda x: x.str.encode('ascii', 'ignore').str.decode('ascii')) #remove emojis by ignoring the ascii values
df["Review text"] = df['Review text'].str.replace('[^\w\s]','') #remove puntuations

In [115]:
df.replace(to_replace=[r"\\t|\\n|\\r", "\t|\n|\r"], value=[" ", " "], regex=True, inplace=True) #remove \n \t characters

In [116]:
df

            Name                                        Review text
0     Mustafa Y.  Luminous is very Awesome Portability is very n...
1         SULTAN  literally i got the thing beyond my expectatio...
2          ****7  Awesome productI personally like this And it d...
3        muzamil  Seems to be a good product just received in a ...
4          Z***.  light bht achi haporey room ko achi trha rosha...
5     Huzaifa G.  it is a amazing lamp its helps me alot in my s...
6       TARIQ M.  Amazing beautiful smart product packed careful...
7        Saad M.  same product as shown in the picture very sati...
8    Muhammad A.  Original product  The seller is trustworthy as...
9         Ali R.  Quality  1010 Delivery 1010 Product experience...
10      Talha J.  Very good product especially in this price ran...
11         3***5  Good for 800ish Pkr I think Two problems One i...
12       Äñäs M.  unexpectedly extreme quality product in such a...
13   Muhammad K.  Reviewing after 1 month of use  I am working l...
14  jahanzaib A.  This product is really amazing   Great result ...

In [158]:
import nltk
#nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\asimf\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [83]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [117]:
r, c = df.shape #getting rows and cols

In [118]:
sentiments=[] 
sid = SentimentIntensityAnalyzer()
for row in range(0,r):
    temp=sid.polarity_scores(df['Review text'][row])
    if temp['compound'] >=0:
        sentiments.append('Positive')
    else:
        sentiments.append('Negative')

In [119]:
df['Sentiment']=sentiments

In [120]:
df #final

            Name                                        Review text Sentiment
0     Mustafa Y.  Luminous is very Awesome Portability is very n...  Positive
1         SULTAN  literally i got the thing beyond my expectatio...  Positive
2          ****7  Awesome productI personally like this And it d...  Positive
3        muzamil  Seems to be a good product just received in a ...  Positive
4          Z***.  light bht achi haporey room ko achi trha rosha...  Positive
5     Huzaifa G.  it is a amazing lamp its helps me alot in my s...  Positive
6       TARIQ M.  Amazing beautiful smart product packed careful...  Positive
7        Saad M.  same product as shown in the picture very sati...  Positive
8    Muhammad A.  Original product  The seller is trustworthy as...  Positive
9         Ali R.  Quality  1010 Delivery 1010 Product experience...  Positive
10      Talha J.  Very good product especially in this price ran...  Positive
11         3***5  Good for 800ish Pkr I think Two problems One i...  Positive
12       Äñäs M.  unexpectedly extreme quality product in such a...  Positive
13   Muhammad K.  Reviewing after 1 month of use  I am working l...  Positive
14  jahanzaib A.  This product is really amazing   Great result ...  Positive

# Question 2   (20 marks)

Scrape 80 items for a keyword search e.g., 'mobile covers'<br/>Note: Must use "click()" function of webElement, URL changing for pages is not allowed. The code must be generic and should work for every keyword, with proper checks in place. Bonus for also scraping country and Daraz Mall availability.

In [4]:
query = 'mobile covers'
query = query.replace(' ','+') #replacing query space with + as chrome takes it as space in url
url = f'https://www.daraz.pk/catalog/?q={query}&_keyori=ss&from=input&spm=a2a0e.pdp.search.go.488ahLL6hLL6fD'
print(url)

https://www.daraz.pk/catalog/?q=mobile+covers&_keyori=ss&from=input&spm=a2a0e.pdp.search.go.488ahLL6hLL6fD

In [35]:
warnings.filterwarnings("ignore") #igonoring window warning
driver = webdriver.Chrome(executable_path=r"C:\Users\asimf\Downloads\chromedriver.exe")

In [36]:

driver.get(url) #load the url

In [28]:
def scroll(): # a function to slowly scroll down the page, this is useful when the page is not loaded properly and the wifi is slow
    total_page_height = driver.execute_script("return document.body.scrollHeight") #take height of the [age]
    browser_window_height = driver.get_window_size(windowHandle='current')['height'] #window size
    current_position = driver.execute_script('return window.pageYOffset') #current positon
    while total_page_height - current_position > browser_window_height:
        driver.execute_script(f"window.scrollTo({current_position}, {browser_window_height + current_position});")
        current_position = driver.execute_script('return window.pageYOffset')
        time.sleep(1) #this is an important step to scroll down slowly

In [62]:
names = []
reviews = []
stars = []
prices = []
countries = []
avail=[]
i=1 #for looping 81 times
cn=1 #for looping 40 times on each page, will be set to zero when 2nd page starts

while(i<=80):
    time.sleep(5)
    try:
        av=driver.find_element("xpath",f'/html/body/div[3]/div/div[2]/div/div/div[1]/div[2]/div[{cn}]/div/div/div[2]/div[1]/i') #get daraaz mall availbility
        av="Available"
    except ValueError:
        av = 'Private'
    except NoSuchElementException:
        av="Private"
    avail.append(av)
    
    try: #get country
        country=driver.find_element("xpath",f"/html/body/div[3]/div/div[2]/div/div/div[1]/div[2]/div[{cn}]/div/div/div[2]/div[5]/span").text
        if country=="Free Shipping": #if it is free shipping means fromoverseas
            country="Overseas"
    except ValueError:
        country = 'Not Available'
    countries.append(country)
    try: #select the item
        b=driver.find_element("xpath", f'/html/body/div[3]/div/div[2]/div/div/div[1]/div[2]/div[{cn}]/div/div/div[1]/div[1]/a/img')
        b.click()
        time.sleep(5)
    except ElementClickInterceptedException:
        print("No item")
        #break
    except NoSuchElementException:
        print("No such element l")
        break
        
    print(i)
    
    try: #get name
        name=driver.find_element(By.CLASS_NAME,"pdp-mod-product-badge-title").text
    except ValueError:
        name = 'Not Available'
    names.append(name)
    
    try: #get price
        price=driver.find_element("xpath",'/html/body/div[4]/div/div[3]/div[2]/div/div[1]/div[7]/div/div/span')
        price=price.text[4:]
    except ValueError:
        price=' '
    prices.append(price)
    
    try:#get review
        rev=driver.find_element("xpath", '//*[@id="module_product_review_star_1"]/div/a[1]')
        rev=rev.text.split()
        rev_int=int(rev[0])
    except ValueError:
        rev_int = 0
    
    reviews.append(rev_int)
    scroll() #scroll is needed before getting stars as the page needs to get loaded properly 
    time.sleep(3)
    try: #get stars
        star=driver.find_element("xpath",'/html/body/div[4]/div/div[9]/div[1]/div[2]/div/div/div/div[1]/div[2]/div/div/div[1]/div[1]/span[1]').text
    except NoSuchElementException:
        star=0
    stars.append(star)
    i=i+1
    cn=cn+1
    driver.back() #go back
    #if(i>8):
    #    scroll()
    if(i==41): #go to 2nd page
        try:
            cn=1
            c=driver.find_element("xpath","/html/body/div[3]/div/div[2]/div/div/div[1]/div[3]/div/ul/li[3]/a")
            c.click()
            print("page 2")
        except ElementClickInterceptedException:
            print("No page")
            break
        except NoSuchElementException:
            print("No such element j")
            break
    
driver.close()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
page 2
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80

In [70]:
#names
#countries
#prices
#reviews
#stars
#avail

In [72]:
df = pd.DataFrame({'Name':names,'Price':prices,'Stars':stars,'Reviews':reviews,'Countries':countries,'Availbility':avail})

In [73]:
#Output
df

,Name,Price,Stars,Reviews,Countries,Availbility
0,Hontinga for Samsung A31 Case Luxury 6D Platin...,506,4.7,60,Overseas,Available
1,Hontinga for Huawei Y9 Prime 2019 Case Luxury ...,441,4.9,147,Overseas,Available
2,Hontinga for OPPO F11 Pro Back Cover Luxury 6D...,524,4.6,17,Overseas,Available
3,Hontinga for Samsung Galaxy A03 Back Cover Lux...,445,5.0,40,Overseas,Available
4,Blue Sky Store For Samsung Galaxy A13 Vintage ...,"1,000",4.9,18,China,Private
...,...,...,...,...,...,...
75,TA for OPPO F17 Pro A93 2020 Back Cover Luxury...,445,4.9,56,China,Private
76,Jizetin for OPPO A52 A92 Back Cover Luxury 6D ...,445,4.9,23,China,Available
77,Hontinga for Vivo Y33S Y21 2021 Y21S Y21T Y21A...,524,4.8,115,Overseas,Available
78,Hontinga for Vivo Y15A Y15S Y15C Y01 Back Cove...,515,5.0,8,Overseas,Available
79,iPhone 7+/ 8+ Silicone Mobile Cover Compatible...,479,4.9,16,Overseas,Private

# Question 3  (30 marks)

<!-- Which Products are on Flash sale? Display Product name, Actual Price, Discounted Price, Discount Percentage, Rating, No. of Reviews, Top 3 reviews displayed.

Display output must be like this. Products may vary. -->

If a user wants to make a store to sell something, lets say "Mobile Covers". He/She wants to see folowing things:
1. Top 10 Sellers store names
2. Daraz Mall Store/ Private store
3. Total "Mobile Covers" listings on his store
4. Avg Prices
5. Avg Units selling
6. Positive Seller Ratings
7. Seller Country

In [62]:
query = 'mobile covers'
query = query.replace(' ','+') #replacing query space with + as chrome takes it as space in url
url = f'https://www.daraz.pk/catalog/?q={query}&_keyori=ss&from=input&spm=a2a0e.pdp.search.go.488ahLL6hLL6fD'
print(url)

https://www.daraz.pk/catalog/?q=mobile+covers&_keyori=ss&from=input&spm=a2a0e.pdp.search.go.488ahLL6hLL6fD

In [63]:
def scroll(): # a function to slowly scroll down the page, this is useful when the page is not loaded properly and the wifi is slow
    total_page_height = driver.execute_script("return document.body.scrollHeight") #take height of the [age]
    browser_window_height = driver.get_window_size(windowHandle='current')['height'] #window size
    current_position = driver.execute_script('return window.pageYOffset') #current positon
    while total_page_height - current_position > browser_window_height:
        driver.execute_script(f"window.scrollTo({current_position}, {browser_window_height + current_position});")
        current_position = driver.execute_script('return window.pageYOffset')
        time.sleep(1) #this is an important step to scroll down slowly

In [64]:
warnings.filterwarnings("ignore") #igonoring window warning
driver = webdriver.Chrome(executable_path=r"C:\Users\asimf\Downloads\chromedriver.exe")

In [65]:
driver.get(url)

In [66]:
from statistics import mean #for calculating average price quickly
countries=[]
seller=[]
Listings=[]
name=[]
prices=[]
priceTemp=[]
cnt=1
followers=[]
avail=[]
label=1
while(label<=10): #10 brands
    print(label)
    time.sleep(10)
    c=driver.find_element("xpath",f'/html/body/div[3]/div/div[2]/div/div/div[2]/div/div[2]/div[2]/div/div[1]/label[{label}]/span[1]/input')
    c.click() 
    time.sleep(7)
    try: #get country
        country=driver.find_element("xpath","//*[@id='root']/div/div[2]/div/div/div[1]/div[3]/div[1]/div/div/div[2]/div[5]/span").text
        if country=="Free Shipping": #if it is free shipping means fromoverseas
            country="Overseas"
    except ValueError:
        country = 'Not Available'
    countries.append(country)
    #get number of lists
    li=driver.find_element("xpath","//*[@id='root']/div/div[2]/div/div/div[1]/div[1]/div/div[1]/div/div/span[1]").text
    li=li.split()
    Listings.append(li[0])
    #click product
    try:
    
        g=driver.find_element("xpath", '/html/body/div[3]/div/div[2]/div/div/div[1]/div[3]/div[1]/div/div/div[1]/div[1]/a/img')
        g.click()
        time.sleep(7)
    except ElementClickInterceptedException:
        print("No item")
        #break
    except NoSuchElementException:
        print("No such element l")
        #break
     #get seller percentage   
    s=driver.find_element("xpath",'/html/body/div[4]/div/div[3]/div[2]/div/div[2]/div[5]/div/div[2]/div[1]/div[2]').text
    seller.append(s)
    try:
        g=driver.find_element("xpath",'/html/body/div[6]/div/div[2]/div/span/i')
        g.click()
    except NoSuchElementException:
        print("No such add")
        
    except ElementClickInterceptedException:
        print("No add")
    
    
    #scroll()
    #click to see store info
    try:
        b=driver.find_element("xpath", '/html/body/div[4]/div/div[3]/div[2]/div/div[2]/div[5]/div/div[3]/a')
        time.sleep(5)
        b.click()
        time.sleep(5)
    except ElementClickInterceptedException:
        print("No item")
        #break
    except NoSuchElementException:
        print("No such element l")
        #break
        
    time.sleep(10)
    #get name
    n=driver.find_element("xpath",'/html/body/div[3]/div/div/div[2]/div/div/div/div[2]/div[1]/div/div/div/div[2]/div[1]/h1').text
    name.append(n)
    #get followers
    f=driver.find_element("xpath",'/html/body/div[3]/div/div/div[2]/div/div/div/div[2]/div[1]/div/div/div/div[2]/div[2]/div').text
    f=f.split()
    followers.append(f[0])
    try:
        a=driver.find_element("xpath",'/html/body/div[3]/div/div/div[2]/div/div/div/div[2]/div[1]/div/div/div/div[2]/div[2]/img').text
        a="Daraz Mall"
    except ValueError:
        a = 'Private'
    except NoSuchElementException:
        a="Private"
    avail.append(a)
    driver.back()
    time.sleep(2)
    driver.back()
    time.sleep(2)
    
    scroll()
    time.sleep(2)
    cnt=1
    while(cnt<=40): #get first page prices and get mean to have an over all estimate, i know this is not the best approach but i could think of doing this way only
        try:
            pricy=driver.find_element("xpath",f'/html/body/div[3]/div/div[2]/div/div/div[1]/div[3]/div[{cnt}]/div/div/div[2]/div[3]/span').text
            pricy=pricy.split()
            pricy=int(pricy[1])
        except ValueError:
            pricy=0   
        except NoSuchElementException:
            print("No such element l")
            break
        cnt=cnt+1
        priceTemp.append(pricy)
    prices.append(mean(priceTemp))
    driver.back()
    #c=driver.find_element("xpath",f'/html/body/div[3]/div/div[2]/div/div/div[2]/div/div[2]/div[2]/div/div[1]/label[{label}]/span[1]/input')
    #c.click() 
    time.sleep(5)
    label=label+1
    if(label>8): #click show more
        try:
            c=driver.find_element("xpath",'/html/body/div[3]/div/div[2]/div/div/div[2]/div/div[2]/div[2]/div/div[2]')
            c.click()
        except ElementClickInterceptedException:
            print("more less no")
            
driver.close()

1
2
No such add
3
No such add
4
No such add
5
No such add
6
No such add
7
No such add
No such element l
8
No such add
9
No such add
10
No such add

In [40]:
#countries
#seller
#Listings
name
#followers
#avail

['Hontinga',
 'Jizetin Official Store',
 'UCUC',
 'FELMYST',
 'Lenuo',
 'Lereach',
 'Biruiqu',
 'Relaxtoo',
 'Leweisi',
 'Nillkin']

In [71]:
import math
df = pd.DataFrame({'Store Name':name,'Daraz Mall/Private':avail,'Avg Price':prices,'Listings':Listings,'Seller Ratings':seller,'Country':countries,'Followers':followers})
df['Avg Price']=df['Avg Price'].round(2)

In [72]:
df

,Store Name,Daraz Mall/Private,Avg Price,Listings,Seller Ratings,Country,Followers
0,Hontinga,Daraz Mall,477.12,195380,93%,Overseas,30623
1,Jizetin Official Store,Daraz Mall,482.45,57860,94%,China,4263
2,UCUC,Daraz Mall,473.77,64517,93%,Overseas,7915
3,FELMYST,Daraz Mall,466.57,55036,92%,China,1826
4,Lenuo,Daraz Mall,484.50,4714,91%,Overseas,14895
5,Lereach,Daraz Mall,522.50,2976,89%,Overseas,2665
6,Biruiqu,Private,532.46,6,88%,China,5911
7,Relaxtoo,Daraz Mall,530.54,270,86%,Overseas,548
8,Leweisi,Private,537.07,150,94%,China,381
9,Nillkin,Daraz Mall,478.76,259,92%,Overseas,13151

In [97]:
#Run this cell to see the sample output
import pandas as pd
pd.read_csv('output.csv')

,Store Name,Daraz Mall/Private,Avg Price,Listings,Avg unit selling,Seller Ratings,Country,Followers
0,Hontinga,Daraz Mall,565,187414,110,93,Overseas,29919
1,ABC MOBILE ACCESSORIES STORE ( FAISALABAD ),Private,95,438,29,93,Pakistan,11969